name: refillproo
description: A new Flutter project

publish_to: 'none' # Remove this line if you are publishing the package

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  location: ^8.0.0
  geolocator: ^13.0.4
  permission_handler: ^11.4.0
  http: ^1.3.0
  logging: ^1.3.0
  cupertino_icons: ^1.0.8 # Ensure this is correctly aligned and not commented out
  shared_preferences: ^2.5.3
  logger: ^2.5.0
  convert: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  # image_path_android: "assets/icon/android_icon.png"
  # image_path_ios: "assets/icon/ios_icon.png"
    

flutter:
  uses-material-design: true

  assets:
    - images/
    - assets/images/
    - assets/images/regular_gallon.png
    - assets/images/dispenser_gallon.png
    - assets/images/small_gallon.png
    - assets/icon/app_icon.png
    - images/location1.jpg
    - images/order_msg.png

